const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const INCORRECT_PASSWORD = "INCORRECT_PASSWORD";
const USER_NOT_FOUND = "USER_NOT_FOUND";
const LOGOUT_FAILED = "LOGOUT_FAILED";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  INCORRECT_PASSWORD,
  USER_NOT_FOUND,
  LOGOUT_FAILED,
  LOGOUT_SUCCESS
}
